server:
  port: 80

  # Response data gzip.
  compression:
    enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/idea?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
# H2 database configuration.
  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:file:~/.halo/db/halo
  #    username: admin
  #    password: 123456


  # H2 database console configuration.
#  h2:
#    console:
#      settings:
#        web-allow-others: false
#      path: /h2-console
#      enabled: false

halo:

  # Your admin client path is https://your-domain/{admin-path}
  admin-path: admin

  # memory, level, redis
  cache: memory
